---
# start first control ndoe
- name: initialize master
  ansible.builtin.command: "kubeadm init --upload-certs --control-plane-endpoint={{ k8apiendpoint }} --service-dns-domain={{ k8servicedomain }} --skip-phases=addon/kube-proxy --pod-network-cidr={{ k8podcidr }}"
  register: kubeadm_init

- name: validation
  ansible.builtin.debug:
    var: kubeadm_init

# Link the admin.conf so that kubectl commands work
- name: Ensure .kube directory exists.
  file:
    path: ~/.kube
    state: directory

- name: Symlink the kubectl admin.conf to ~/.kube/conf.
  file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link
    
# The standard token command doesn't work. Needs some method of interpretting the output of kubeadm init. Pause and copy the debug output from screen
- name: Join other control plane
  ansible.builtin.pause:
    prompt: "Copy the kubeadm join for the control from the above debug message and execute on the other controller"