---
# Test for docker repo
- name: Docker repo test
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/docker.sources
  register: docker_repo

# Install docker repo
- include_tasks: docker-repo.yml
  when: not docker_repo.stat.exists

# Test for the containerd configuration file
- name: containerd test
  ansible.builtin.stat:
    path: /etc/containerd/config.toml
  register: containerd_installed

# Install containerd
- include_tasks: containerd-install.yml
  when: not containerd_installed.stat.exists

- name: Reboot
  ansible.builtin.reboot:
